# Assignment 9 - Clustering

## Tasks

### Task 1

- **What type of algorithm did we use in exercise 1?**

For exercise one we use the AgglomerativeClustering algoritm which is the "bottom-up" algoritm.

- **How many types of hierarchical clustering are you familiar with?**

Currently i am familiar with the Agglomerative and the Divisible algoritms

- **How do they differ?**

So as before mentioned, the agglomerative uses the "bottom-up" approach, meaning that each point starts out as its own cluster, and from there, we cluster these together depending on how close they are to each other, to make bigger clusters.
The other one is the divisible algoritm which is the opposite, and starts with only one cluster which is the whole dataset, and divides these into smaller and smaller clusters.

### Task 2

In [36]:
import numpy as np
import pandas as pd

from sklearn.cluster import  MeanShift, estimate_bandwidth

from sklearn import metrics
import matplotlib.pyplot as plt


from scipy.spatial.distance import cdist

import seaborn as sns
import plotly.express as pxp
import plotly.graph_objs as gph

In [37]:
df = pd.read_csv("soft2022spring-DS/Data/freedom.csv")
print(df.shape)
df.head()

(193, 48)


country  1972  1973  1974  1975  1976  1977  1978  1979  1980  ...  \
0  Afghanistan   4.5   6.5   6.5   6.5   6.5   6.0   7.0   7.0   7.0  ...   
1      Albania   7.0   7.0   7.0   7.0   7.0   7.0   7.0   7.0   7.0  ...   
2      Algeria   6.0   6.0   6.0   6.5   6.0   6.0   6.0   6.0   6.0  ...   
3      Andorra   3.5   4.0   4.0   4.0   4.0   NaN   NaN   NaN   NaN  ...   
4       Angola   NaN   NaN   NaN   6.0   6.0   7.0   7.0   7.0   7.0  ...   

   2009  2010  2011  2012  2013  2014  2015  2016  2017  2018  
0   6.0   6.0   6.0   6.0   6.0   6.0   6.0   6.0   5.5   5.5  
1   3.0   3.0   3.0   3.0   3.0   3.0   3.0   3.0   3.0   3.0  
2   5.5   5.5   5.5   5.5   5.5   5.5   5.5   5.5   5.5   5.5  
3   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0  
4   5.5   5.5   5.5   5.5   5.5   5.5   6.0   6.0   6.0   5.5  

[5 rows x 48 columns]

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 193 entries, 0 to 192
Data columns (total 48 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   country  193 non-null    object 
 1   1972     142 non-null    float64
 2   1973     143 non-null    float64
 3   1974     145 non-null    float64
 4   1975     151 non-null    float64
 5   1976     152 non-null    float64
 6   1977     148 non-null    float64
 7   1978     151 non-null    float64
 8   1979     154 non-null    float64
 9   1980     155 non-null    float64
 10  1981     157 non-null    float64
 11  1982     0 non-null      float64
 12  1983     158 non-null    float64
 13  1984     159 non-null    float64
 14  1985     159 non-null    float64
 15  1986     159 non-null    float64
 16  1987     159 non-null    float64
 17  1988     159 non-null    float64
 18  1989     160 non-null    float64
 19  1990     160 non-null    float64
 20  1991     179 non-null    float64
 21  1992     183 non

#### Clean data

In [39]:
column_means = df.mean()
df = df.fillna(column_means)
df.isna().sum()

C:\Users\Mathias\AppData\Local\Temp/ipykernel_8624/3021921920.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  column_means = df.mean()


country      0
1972         0
1973         0
1974         0
1975         0
1976         0
1977         0
1978         0
1979         0
1980         0
1981         0
1982       193
1983         0
1984         0
1985         0
1986         0
1987         0
1988         0
1989         0
1990         0
1991         0
1992         0
1993         0
1994         0
1995         0
1996         0
1997         0
1998         0
1999         0
2000         0
2001         0
2002         0
2003         0
2004         0
2005         0
2006         0
2007         0
2008         0
2009         0
2010         0
2011         0
2012         0
2013         0
2014         0
2015         0
2016         0
2017         0
2018         0
dtype: int64

In [54]:
X1 = df.iloc[:, -1:].values
X2 = df.iloc[:, 1:2].values
X = np.concatenate((X1,X2), axis=1)

#### Train a model

In [55]:
# Bandwidth is found automatically with
bandwidth = estimate_bandwidth(X, quantile=0.2, n_samples=200)

In [56]:
# Train mean-shift model with the data frame
msmodel = MeanShift(bandwidth=bandwidth, bin_seeding=True)
msmodel.fit(X)
labels = msmodel.labels_
labels_unique = np.unique(labels)
n_clusters_ = len(labels_unique)
n_clusters_

3

In [57]:
# See the clusters and cluster centres
cluster_centers = msmodel.cluster_centers_
cluster_centers

array([[2.07246377, 4.5460298 ],
       [6.0754717 , 5.71306139],
       [1.5125    , 1.7125    ]])

In [58]:
# Predict the cluster for all the samples
Y = msmodel.predict(X)
Y

array([1, 0, 1, 0, 1, 0, 0, 0, 2, 2, 1, 0, 1, 1, 2, 1, 2, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 2, 0, 1, 1, 2, 1, 2, 0, 1, 1, 2, 1, 0, 1,
       2, 0, 2, 1, 0, 2, 0, 1, 2, 1, 1, 0, 1, 1, 2, 2, 2, 1, 2, 0, 0, 0,
       0, 0, 2, 1, 1, 2, 1, 0, 0, 2, 2, 0, 1, 1, 2, 2, 2, 2, 2, 1, 1, 0,
       0, 1, 1, 1, 0, 2, 0, 0, 1, 2, 0, 2, 0, 0, 2, 1, 1, 2, 0, 1, 2, 0,
       0, 0, 2, 0, 0, 1, 0, 1, 0, 2, 0, 2, 2, 1, 1, 0, 1, 0, 2, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 2, 2, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 2, 0, 0, 0, 1, 0, 2, 2, 1, 1, 1, 1, 0, 1, 2, 2,
       0, 1, 1, 0, 1, 0, 1, 2, 2, 0, 1, 0, 1, 1, 1, 0, 1], dtype=int64)

In [59]:
len(msmodel.labels_)

193

In [60]:
# Predict the cluster for all the samples
P = msmodel.predict(X)
P

array([1, 0, 1, 0, 1, 0, 0, 0, 2, 2, 1, 0, 1, 1, 2, 1, 2, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 2, 0, 1, 1, 2, 1, 2, 0, 1, 1, 2, 1, 0, 1,
       2, 0, 2, 1, 0, 2, 0, 1, 2, 1, 1, 0, 1, 1, 2, 2, 2, 1, 2, 0, 0, 0,
       0, 0, 2, 1, 1, 2, 1, 0, 0, 2, 2, 0, 1, 1, 2, 2, 2, 2, 2, 1, 1, 0,
       0, 1, 1, 1, 0, 2, 0, 0, 1, 2, 0, 2, 0, 0, 2, 1, 1, 2, 0, 1, 2, 0,
       0, 0, 2, 0, 0, 1, 0, 1, 0, 2, 0, 2, 2, 1, 1, 0, 1, 0, 2, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 2, 2, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 2, 0, 0, 0, 1, 0, 2, 2, 1, 1, 1, 1, 0, 1, 2, 2,
       0, 1, 1, 0, 1, 0, 1, 2, 2, 0, 1, 0, 1, 1, 1, 0, 1], dtype=int64)

In [61]:
# For serialization and deserialization of data from/to file
# from sklearn.externals import joblib
import joblib
joblib.dump(msmodel, 'deploy/msmodelAS9.pkl')

['deploy/msmodelAS9.pkl']

This would have deployed the model in a file.

#### Task is continued in "Assignment 9 part 2"